POST http://localhost:3000/goals
Content-Type: application/json

{
  "title": "Aprender Node.js y Express desde cero",
  "desiredWeeklyFrequency": 2
}

###

POST http://localhost:3000/completions
Content-Type: application/json

{
  "goalId": "iboiltyxydvdg14a2jpo8uba"
}

###
GET http://localhost:3000/pending-goals


###
GET http://localhost:3000/summary