name: in-orbit

services:
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: inorbit
      POSTGRES_PASSWORD: inorbit
      POSTGRES_DB: inorbit